### ISSUE TITLE
 Distance function 

### ISSUE THREAD

**Issue by 89z** [ajdnik/imghash#4]
Similar to these:

https://pkg.go.dev/github.com/corona10/goimagehash#ImageHash.Distance

https://pkg.go.dev/github.com/Nr90/imgsim#Distance

**Comment by ajdnik** [comment]
@89z Both of the implementations you listed implement a [Hamming distance](https://en.wikipedia.org/wiki/Hamming_distance) metric which this library already implements in [similarity.Hamming](https://pkg.go.dev/github.com/ajdnik/imghash@v1.0.0/similarity#Hamming), besides the Hamming distance the library implements [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) metric, more commonly known as L2 in [similarity.L2Float64](https://pkg.go.dev/github.com/ajdnik/imghash@v1.0.0/similarity#L2Float64) and [similarity.L2Uint8](https://pkg.go.dev/github.com/ajdnik/imghash@v1.0.0/similarity#L2UInt8), as well as [Peak Correlation Coefficient](https://en.wikipedia.org/wiki/Cross-correlation) distance in [similarity.PCCFloat64](https://pkg.go.dev/github.com/ajdnik/imghash@v1.0.0/similarity#PCCFloat64) and [similarity.PCCUint8](https://pkg.go.dev/github.com/ajdnik/imghash@v1.0.0/similarity#PCCUInt8).

For an understanding of which distance to use with which hashing function, please look at the tests for each hashing function, each of them has `Distance` tests implemented.
